---
all:
  children:
    dnsmasq:
      hosts:
        dnsmasq_vm:
          ansible_host: 192.168.1.36
      vars:
        ansible_user: debian
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    maas:
      hosts:
        maas_vm:
          ansible_host: 192.168.1.37
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519

