name: Apply Terraform 
on:
  push:
    paths:
      - 'cloudflare/**'
      - ".github/workflows/**"

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cloudflare

    env:
      TF_VAR_cloudflare_token: ${{ secrets.CLOUDFLARE_TOKEN_YUKARIUK_TUNNEL }}
      TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID_YUKARIUK }}
      TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      TF_VAR_cloudflare_idp_github_id: ${{ secrets.CLOUDFLARE_IDP_GITHUB_ID }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}

      - name: initialize
        run: |
          terraform init
      - name: validate
        run: |
          terraform validate

      - name: plan
        run: terraform plan -no-color -input=false
