name: Check Proxmox Terraform manifest
on:
  push:
    paths:
      - "proxmox/main.tf"
      - ".github/workdlows/**"

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: proxmox
    env:
      TF_VAR_pm_api_url: ${{ vars.PROXMOX_URL }}
      PROXMOX_URL: ${{ vars.PROXMOX_URL }}
      TF_VAR_pm_api_token_id: ${{ vars.PROXMOX_API_TOKEN_ID }}
      TF_VAR_pm_api_token_secret: ${{ secrets.PROXMOX_API_TOKEN_SECRET }}
      TF_VAR_pm_ssh_public_key: ${{ secrets.PROXMOX_SSH_PUBKEY }}
      TF_VAR_pm_ssh_private_key: ${{ secrets.PROXMOX_SSH_PRIVKEY }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install mitmproxy
        run: |
          sudo apt install mitmproxy

      - name: create mitmproxy yaml
        env:
          CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets. CF_ACCESS_CLIENT_SECRET }}
        run: |
          mkdir -p ~/.mitmproxy
          ./create_mitmproxy_yaml.sh > ~/.mitmproxy/config.yaml
      - name: start mitmproxy
        run: |
          screen -dmS proxy mitmproxy
          sleep 5

      - name: setup mitm CA cert
        run: |
          openssl x509 -in ~/.mitmproxy/mitmproxy-ca-cert.pem -inform PEM -out out.crt
          sudo mkdir /usr/local/share/ca-certificates/extra
          sudo cp out.crt /usr/local/share/ca-certificates/extra
          sudo dpkg-reconfigure ca-certificates --frontend noninteractive
          sudo update-ca-certificates

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}

      - name: initialize
        run: |
          terraform init
      - name: validate
        run: |
          terraform validate

      - name: plan
        run: terraform plan -no-color -input=false
        env:
          HTTPS_PROXY: 'http://localhost:8080'
